{{- $identity := get .Values.global "identity" | default (dict) -}}
{{- $externalIdentity := get $identity "external" | default (dict) -}}
{{- $identityClients := get $externalIdentity "clients" | default (dict) -}}
{{- $trinoIdentity := get $identityClients "trino" | default (dict) -}}
{{- $identityEnabled := and (default false $identity.enabled) (default false $trinoIdentity.enabled) -}}
{{- $legacyPasswordAuthRequested := contains "PASSWORD" (default "" .Values.server.config.authenticationType) -}}
{{- $passwordAuthRequested := or (default false $trinoIdentity.passwordAuthEnabled) $legacyPasswordAuthRequested -}}
{{- if and (not (and $identityEnabled $passwordAuthRequested)) (not .Values.auth.passwordAuthSecret) .Values.auth.passwordAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.passwordSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.passwordAuth }}
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}
{{- end }}
---
{{- if and (not .Values.auth.groupsAuthSecret) .Values.auth.groups }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.groupsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
{{- end }}
{{- end }}
