{{- if .Values.datahub.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: prerequisites-kafka
  labels:
    {{- include "dlh-in-a-box.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "dlh-in-a-box.datahubPrerequisites.kafkaFQDN" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: prerequisites-zookeeper
  labels:
    {{- include "dlh-in-a-box.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "dlh-in-a-box.datahubPrerequisites.zookeeperFQDN" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: prerequisites-mysql
  labels:
    {{- include "dlh-in-a-box.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "dlh-in-a-box.datahubPrerequisites.mysqlFQDN" . }}

{{- $mysqlAuth := .Values.datahubPrerequisites.mysql.auth | default (dict) -}}
{{- if $mysqlAuth.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "mysql-secrets" $mysqlAuth.existingSecret }}
  labels:
    {{- include "dlh-in-a-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ $mysqlAuth.rootPassword | quote }}
{{- else if not $mysqlAuth.existingSecret }}
{{- fail "Set datahubPrerequisites.mysql.auth.rootPassword or datahubPrerequisites.mysql.auth.existingSecret when datahub.enabled=true." }}
{{- end }}
{{- end }}
