{{- if and (not .Values.global.storage.existingSecret) (eq .Values.global.storage.backend "externalS3") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dlh-in-a-box.fullname" . }}-storage-config
  labels:
    {{- include "dlh-in-a-box.labels" . | nindent 4 }}
type: Opaque
stringData:
  endpoint: {{ .Values.global.storage.s3.endpoint | quote }}
  region: {{ .Values.global.storage.s3.region | quote }}
  bucket: {{ .Values.global.storage.s3.bucket | quote }}
  pathStyleAccess: {{ .Values.global.storage.s3.pathStyleAccess | quote }}
  {{ .Values.global.storage.s3.accessKeyKey }}: ""
  {{ .Values.global.storage.s3.secretKeyKey }}: ""
{{- end }}
