global:
  environment: prod
  domain: prod.example.com
  identity:
    accessRoles:
      bronze-reader:
        description: Approved read-only users for the bronze catalog.
      bronze-writer:
        description: Approved read-write users for the bronze catalog.
      silver-reader:
        description: Approved read-only users for the silver catalog.
      silver-writer:
        description: Approved read-write users for the silver catalog.
      geospatial-reader:
        description: Approved read-only users for the geospatial catalog.
      geospatial-writer:
        description: Approved read-write users for the geospatial catalog.
  authorization:
    ranger:
      enabled: true
  storage:
    backend: externalS3
    s3:
      endpoint: https://s3.example.com
      region: us-east-1
      pathStyleAccess: true
      existingSecret: dlh-prod-object-store-credentials
  dataCatalogs:
    bronze:
      type: deltaLake
      warehouseDir: s3a://dlh/warehouse/bronze
    silver:
      type: deltaLake
      warehouseDir: s3a://dlh/warehouse/silver
    gold:
      type: deltaLake
      warehouseDir: s3a://dlh/warehouse/gold
    geospatial:
      type: hive
      warehouseDir: s3a://dlh/warehouse/geospatial

prefectWorker:
  worker:
    replicaCount: 3
    config:
      workPool: kubernetes-prod
      workQueues:
        - critical

vault:
  enabled: true

minio:
  enabled: false

datahub:
  enabled: false

hive:
  enabled: true
