global:
  storage:
    backend: externalS3
    s3:
      endpoint: https://s3-compatible.example.net
      region: us-east-1
      bucket: lakehouse-shared
      pathStyleAccess: true
      accessKey: ""
      secretKey: ""

minio:
  enabled: false
