global:
  environment: dev
  domain: dev.local
  storage:
    backend: externalS3
    s3:
      endpoint: https://s3.example-dev.local
      region: us-east-1
      bucket: dlh-dev
      pathStyleAccess: true
      accessKey: ""
      secretKey: ""
  dataCatalogs:
    default:
      type: deltaLake
      authorizedUsers:
        read: ["user1", "user2"]
        write: ["admin"]

trino:
  accessControl:
    type: configmap

prefectWorker:
  worker:
    replicaCount: 1
    config:
      workPool: kubernetes-dev
      workQueues:
        - default

datahub:
  enabled: false

hive:
  enabled: false
  metastore:
    image:
      registry: docker.io
      repository: apache/hive
      tag: 3.1.3
  schemainit:
    image:
      registry: docker.io
      repository: apache/hive
      tag: 3.1.3
  postgres:
    host: dlh-postgresql
    port: "5432"
    username: hive
    password: hivepassword
  s3:
    endpoint: https://s3.example-dev.local
    accessKey: ""
    secretKey: ""
  warehouseDir: s3a://dlh-dev/warehouse

minio:
  enabled: false
