apiVersion: v2
name: hive
description: Hive Metastore subchart for data lakehouse
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/sanger-pathogens/dlh-in-a-box-umbrella-helm-chart
annotations:
  org.opencontainers.image.source: https://github.com/sanger-pathogens/dlh-in-a-box-umbrella-helm-chart
  org.opencontainers.image.licenses: Apache-2.0
sources:
  - https://github.com/sanger-pathogens/dlh-in-a-box-umbrella-helm-chart
