{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}