{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.externalDatabase.user | b64enc }}
  password: {{ .Values.externalDatabase.password | b64enc }}
{{- end }}