{{- if not .Values.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}-s3-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  accessKey: {{ .Values.s3.accessKey | b64enc }}
  secretKey: {{ .Values.s3.secretKey | b64enc }}
{{- end }}