name: helm-lint

"on":
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.12.0

      - name: Update dependencies
        run: ./hack/helm-dependency-update.sh

      - name: Lint chart
        run: ./hack/lint.sh

      - name: Render chart
        run: ./hack/template.sh

      - name: Package chart
        run: ./hack/package.sh
