name: helm-lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Update dependencies
        run: ./hack/helm-dependency-update.sh

      - name: Lint chart
        run: ./hack/lint.sh

      - name: Render chart
        run: ./hack/template.sh

      - name: Package chart
        run: ./hack/package.sh
