name: helm-lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Update dependencies
        run: ./hack/helm-dependency-update.sh

      - name: Lint chart
        run: ./hack/lint.sh

      - name: Render chart
        run: ./hack/template.sh

      - name: Package chart
        run: ./hack/package.sh
